### ISSUE TITLE
AttributeError when testing JSON templates

### ISSUE THREAD

**Issue by yabusygin** [yabusygin/templtest#20]
`templtest` exits with `AttributeError` exception when testing JSON templates.

For example when testing the following template:

```json
{
    "foo": "{{ foo|default('bar') }}"
}
```

The excepion bellow occures:

```
Traceback (most recent call last):
<...>
  File "<...>/templtest/__main__.py", line 19, in <module>
    main()
  File "<...>/templtest/cli.py", line 42, in main
    test.run()
  File "<...>/templtest/test.py", line 79, in run
    b=actual.splitlines(),
AttributeError: 'dict' object has no attribute 'splitlines'
```

**Comment by yabusygin** [comment]
This happens because `template()` method of `ansible.template.Templar` is called with default value of `convert_data` argument (`True`).
